#!/bin/bash

# custom rofi options
_rofi () {
    rofi -regex -tokenize -i -lines 6 -width 50% -height 30% -padding 10 -separator-style none -no-levenshtein-sort "$@"
}

# set root directory
noteroot="$HOME/.todo"

# where to store done todos
done_notes="${noteroot}/done"

# set browser
BROWSER="firefox"

# color of title/urls
title_color="#81a2be"

# hotkeys
switch="Alt+Tab"
new="Alt+n"

# maximum length of shown url
url_length=100
