#!/bin/sh

# Array of packages to install
packages=(
    # Shell Packages
    "zsh"                               # Shell replacement
    "zsh-syntax-highlighting"           # Oh-my-zsh plugin

    # Basic Packages
    "rxvt-unicode-256xresources"        # Terminal emulator
    "ranger"                            # File explorer
    "neofetch"                          # Information fetcher
    "cairo-infinality-ultimate"         # Font rendering improvements
    "fontconfig-infinality-ultimate"    # Font rendering improvements
    "freetype2-infinality-ultimate"     # Font rendering improvements
    "ttf-font-awesome"                  # Icon font
    "ttf-input"                         # Mono font of choice
    "wget"                              # Used to directly download files from the internet
    "unzip"                             # Zip extraction
    "unrar"                             # Rar extraction
    "p7zip"                             # 7z extraction
    "xclip"                             # Clipboard manipulation

    # Window management
    "i3-gaps"                           # Window manager
    "polybar"                           # Workspace display and info bar
    "compton"                           # Compositer
    "rofi"                              # Run menu
    "dunst"                             # Notification daemon
    "lightdm"                           # Simple display manager
    "lightdm-gtk-greeter"               # Greeter for lightdm
    "oomox-git"                         # Numix gtk theme with color changing support

    # Internet Packages
    "firefox"                           # Mozilla web browser

    # Imaging Packages
    "feh"                               # Image viewer and background manager
    "scrot"                             # Screenshotter
    "imagemagick"

    # Music Packages
    "ncmpcpp"                           # Ncurses based music player
    "cava-git"                          # Console based audio visualizer
    "mopidy"                            # Python based music server daemon

    # Communication Packages
    "discord"                           # VoIP client
)

# Array of stows to install
stows=(
    # Home folder stow
    "i3--home"

    # Root folder stows
)

# Ask for super user
sudo -v

# Verify script dependencies
sudo pacman -S --needed --noconfirm base-devel git stow

# Remove conflicts
rm -rf ~/.config/i3

sudo rm -rf /etc/pacman.conf

# Install stows
for i  in ${stows[@]}; do
    if [[ $(echo ${i} | grep "\--home") != "" ]]; then
        stow -d ~/dotfiles -t ~ ${i}
    elif [[ $(echo ${i} | grep "\--root") != "" ]]; then
        sudo stow -d ~/dotfiles -t / ${i}
    fi

    echo "${i} stow installed"
done

# Increase /tmp size to build all packages
sudo mount -o remount,size=4G,noatime /tmp

# Fetch cower key
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 487EACC08557AD082088DABA1EB2638FF56C0C53

# Fetch infinality key
sudo pacman-key -r 962DDE58
sudo pacman-key -f 962DDE58
sudo pacman-key --lsign-key 962DDE58

# Synchronize repos
sudo pacman -Sy

# Build git packages
if [[ $(pacman -Qs pacaur) == "" ]]; then
    buildRoot="/tmp/buildroot"

    #Prepepar build directory
    mkdir -p "${builRoot}"
    cd "${buildRoot}" || exit 1

    # Retrieve source files
    git clone "https://aur.archlinux.org/cower.git"
    git clone "https://aur.archlinux.org/pacaur.git"
    git clone "git://arcetera.moe/disputils.git"

    # Build cower, a pacaur dependency
    cd "${buildRoot}/cower" || exit 1
    makepkg --syncdeps --install --noconfirm

    # Build pacaur, an AUR helper
    cd "${buildRoot}/pacaur" || exit 1
    makepkg --syncdeps --install --noconfirm

    # Build disputils, a display utility
    cd "${buildRoot}/disputils" || exit 1
    make
    sudo make install

    # Clean up build directory
    cd ~ || exit 1
    rm -rf "${buildRoot}"
fi

# Install packages from array thhat are not already installed
for i in ${packages[@]}; do
    if [[ $(pacman -Qs ${i}) == "" ]]; then
        pacaur --noedit -S ${i}
    fi
done

# Change shell to zsh
sudo chsh -s /bin/zsh $(whoami)

# Clear orphaned packages
sudo pacman -Rns $(pacman -Qtdq)

